### ISSUE TITLE
parseJson crashes when stdout is not json

### ISSUE THREAD

**Issue by AVVS** [semantic-release/exec#20]
```
[Semantic release]: Call script NODE_ENV=production yarn build
$ node scripts/build.js
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  56.64 KB  build/static/js/main.c965c6ba.js
  788 B     build/static/css/main.1746b4f4.css

The project was built assuming it is hosted at the server root.
You can control this with the homepage field in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

Find out more about deployment here:

  http://bit.ly/2vY88Kr

[Semantic release]: An error occurred while running semantic-release: { JSONError: Unexpected token $ in JSON at position 0 while parsing near '$ node scripts/build...'
    at module.exports (/home/circleci/repo/node_modules/@semantic-release/exec/node_modules/parse-json/index.js:26:19)
    at publish (/home/circleci/repo/node_modules/@semantic-release/exec/index.js:55:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) name: 'JSONError' }
error Command failed with exit code 1.
```

**Comment by pvdlg** [comment]
What is your semantic-release configuration?
Which command are you trying to run? For which plugin hook (prepare, publish, etc...)?

As mentioned in the README, for several command `stdout` is parsed and expect JSON. If the command you run write things in `stdout` you can redirect that to `stderr` instead with something like `my-command params 1>&2`

**Comment by AVVS** [comment]
I did that workaround you mentioned, but thought it's best to actually do smth like try/catch to avoid that sort of thing

Adjusted config:

```
  "publish": [
    {
      "path": "@semantic-release/npm",
      "npmPublish": false
    },
    {
      "path": "@semantic-release/exec",
      "cmd": "NODE_ENV=production yarn build 1>&2"
    },
    "@semantic-release/git",
    "@semantic-release/github"
  ],
```

Maybe add a specific option for parsing output?

**Comment by pvdlg** [comment]
Yes we could ignore JSON parsing errors. But there is no easy way to know if not returning JSON is expected or not.

If a user wants to return JSON to provide the name and URL of the release but for some reason the command doesn't return the JSON, then it will not be considered a failure and the release process will continue.
But I guess if there is an error the command return a code different than `0` so it should be ok.

The only problem is if the user returns invalid JSON, it would be transparently ignored.
I guess we could log something like "The command xxx didn't return valid JSON, so the content of `stdout` will be ignored"

**Comment by AVVS** [comment]
Yep, either that notice, or just some setup options for json (ie expectJSON)

Because I, personally, just updated the module since I didnt see 2.x.x -> 3.x.x thing, then build started failing. I suspect users who want json parsing would be aware of the option and would be able to configure it themselves (ie fail / vs ignore)
