### ISSUE TITLE
how to access pgkRoot variable in publish exec step?

### ISSUE THREAD

**Issue by tarazansafak** [semantic-release/exec#24]
Hello,

We are using exec to customize publish stage. I was wondering if is there any way to get 'pgkRoot' parameter which was defined in package.json and publish from that folder?

Thanks.

**Comment by pvdlg** [comment]
Do you mean the `pkgRoot` option from https://github.com/semantic-release/npm ?

If you set options at the root of the semantic-release config object you can access them with the `config` parameter in https://github.com/semantic-release/exec/issues/24:
```
my-cmd ${config.pkgRoot}
```

**Comment by pvdlg** [comment]
@tarazansafak did that solved your issue?
