### ISSUE TITLE
Allow to set cwd

### ISSUE THREAD

**Issue by felixfbecker** [semantic-release/exec#40]
This would reduce boilerplate of `cd` at the beginning of `cmd`, if the package is in a subfolder.

**Comment by pvdlg** [comment]
So instead of this
```json
{
  "release": {
    "publish": [
      {
        "path": "@semantic-release/exec",
        "cmd": "cd scripts && publish.sh"
      }
    ]
  }
}
```
You would write that
```json
{
  "release": {
    "publish": [
      {
        "path": "@semantic-release/exec",
        "cmd": "publish.sh",
         "cwd": "scripts"
      }
    ]
  }
}
```

How does it make it better?

**Comment by felixfbecker** [comment]
I just find it more readable. It is more similar to e.g. the `npm` plugin where you specify the `pkgRoot` as a property. It also allows me to define the package root at the top of the configuration file and reference it with a YAML reference (`*pkgRoot`) at multiple places, instead of having to inline it in the `cmd` and repeat it. E.g. imagine a package that is published to both npm and has to run custom commands with the `exec` plugin.

Is there a disadvantage to having this option? It seemed easy to support to me.

**Comment by pvdlg** [comment]
The `cwd` option can now be set when using semantic-release via API: https://github.com/semantic-release/semantic-release/blob/caribou/docs/developer-guide/js-api.md#cwd.

This option will define the directory from which to run semantic-release (by default `process.cwd()`).

We might allow to set that option CLI argument at some point and I think it would be confusing to have both.

We could add a `execRoot` option to avoid the confusion. The exec command would run from `path.resolve(cwd, execRoot)`, `cwd` being the current working directory used by semantic-release. 

But is that much of a common case to have many `exec` definitions that all have to run from a directory which is not the same as the one from which semantic-release runs? If feel like if it's the case it should be defined within the project scope and used directly in the scripts, so this variable can be shared between a build script and publication for example. In such example semantic-release would just run the scripts with `cwd` as the project root, and information about a build directory would be contained only on the project build config (and not in the semantic-release configuration). semantic-release is meant to release, not to deal with the project build inner working, so it's probably better to isolate as much as possible the build config and the release config.

**Comment by felixfbecker** [comment]
Yeah I would say this is common for non-JS languages, since you'll want to avoid publishing the semantic-release config and node_modules. For example, in PowerShell, you need to publish a module from a directory, and there is no way to declare files to be ignored (like `.npmignore`). So you often have the PowerShell module in a subdirectory of the repo, and all config files (and stuff like C# source code) in the root or other subdirectories. I'll then have to run all commands in the subdirectory of the PS module.

**Comment by pvdlg** [comment]
In the scenario that you describe wouldn't it be cleaner if you had a project variable that contains the build directory, so it can be used by the build and publish scripts, without have having to be known by semantic-release?
This way if you change the inner working of your build system, and use a different directory you don't have to change the semantic-release config. That allow to isolate the things specific to the project (like the build dir) from semantic-release.

You would have for example a build script and a publish script like this:
```bash
## Build script
cwd = get_build_dir_config()
cd cwd
./build
```
```bash
## Publish script
cwd = get_build_dir_config()
cd cwd
./publish
```
