### ISSUE TITLE
[Security] Lodash vulnerability

### ISSUE THREAD

**Issue by tiwarishubham635** [semantic-release/exec#401]
This library depends on vulnerable versions of lodash
Here is the detailed information - https://github.com/advisories/GHSA-35jh-r3h4-6jhm

Currently this library uses lodash v4.17.4 which should be updated

**Comment by travi** [comment]
> [!IMPORTANT]
> _please_ use our [security policy](https://github.com/semantic-release/git/security/policy) in the future for potential security related issues.

> Currently this library uses lodash v4.17.4

that version is defined as the lower bound of the defined _range_ for the dependency. the patched version is also in-range. simply update your lockfile. you do not need to depend on an update of this package to update to the latest version

**Comment by tiwarishubham635** [comment]
@travi but if I directly update my lockfile, the changes will be overriden with `npm install`. I am facing issue in this

**Comment by travi** [comment]
i understand that this might not have been clear in my response, but i am not advocating for manually modifying your lockfile directly. you should always use the npm cli to do modifications to the `package-lock.json`.

for example, if you `npm rm semantic-release && npm i semantic-release -D`, you will remove and reinstall in a way that the npm cli will rebuild the tree in your lock file with the latest in-range versions throughout the tree

alternatively, you might consider our recommendation to avoid depending on semantic-release as a dependency that ends up in your lockfile and instead use npx to install as late as possible only when you are executing a release from your CI pipeline
