### ISSUE TITLE
Using multiline ${nextRelease.notes} won't work properly

### ISSUE THREAD

**Issue by jpmschuler** [semantic-release/exec#47]

**Comment by bcg62** [comment]
I'm looking to do this as well, is there a correct way to configure publishCmd with multiline or variables with whitespace?

**Comment by jpmschuler** [comment]
I dunno what the problem was, perhaps it was just missing quotes. I currently use 
```
    "prepare": [
        {
            "path": "@semantic-release/exec",
            "cmd": "my-special-command.sh \"${nextRelease.version}\" \"${nextRelease.notes}\""
        }
    ],
```

**Comment by edgetools** [comment]
I have the same problem on Windows 11 with cmd.exe and powershell 5.1

No matter what I do, any newlines in the string end up breaking apart the command and preventing passing it to powershell

**Comment by EdieLemoine** [comment]
For anyone else who ends up here (like me), you can do something like this to keep your shell script readable and not need an external shell script:

```js
    [
      '@semantic-release/exec',
      {
        verifyReleaseCmd: `sh -c '
          if [ -n "$GITHUB_OUTPUT" ]; then
            echo "last-version=\${lastRelease.version}" >> $GITHUB_OUTPUT
            echo "next-version=\${nextRelease.version}" >> $GITHUB_OUTPUT
            echo "release-type=\${nextRelease.type}" >> $GITHUB_OUTPUT
          else
            echo "GITHUB_OUTPUT does not exist"
          fi
        '`,
      },
    ],
```
In JS, a string contained within backticks can have multiple lines. `sh -c <command>` executes a shell command from an inline string. This string can also contain newlines.

For example:
```shell
> sh -c 'echo hi!'

hi!

> sh -c '
  echo "as you can see"
  
  echo "single quotes in bash can be multiline"
'

as you can see
single quotes in bash can be multiline
```
