### ISSUE TITLE
exec lodash template compilation variables

### ISSUE THREAD

**Issue by Thatkookooguy** [semantic-release/exec#75]
Trying to access one of the variables shown in the example:
```
"publishCmd": "./publish.sh ${nextRelease.version} ${options.branch} ${commits.length} ${Date.now()}"
```

in [this project](https://github.com/kibibit/announce-it) like so:
```
"success": [
      "@semantic-release/github",
      [
        "@semantic-release/exec",
        {
          "successCmd": "npm start -- --branch ${options.branch}"
        }
      ]
    ],
```

when this step run, I see this in the [travis run](https://travis-ci.org/Kibibit/announce-it/jobs/558687651):

```
[11:16:33 PM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/exec"
[11:16:33 PM] [semantic-release] [@semantic-release/exec] › ℹ  Call script npm start -- --branch 
> @kibibit/announce-it@1.1.0-next.10 start /home/travis/build/Kibibit/announce-it
> node ./bin/announce-it-cli.js "--branch"
```

which looks like the template variable wasn't injected there. I tried looking for a test in the `exec.test.js` file to look if this is tested (and see if the variable name is wrong in the docs) but couldn't find anything.

Is there a variable I can inject with the branch name? `options.branch`?

Thanks!

**Comment by pvdlg** [comment]
Which version of semantic-release do you use?

**Comment by pvdlg** [comment]
Closing as no answer provided
