### ISSUE TITLE
stdout content ignored log message crashes azure devops build if using variables

### ISSUE THREAD

**Issue by DanielHabenicht** [semantic-release/exec#80]
In Azure DevOps certain variables can be set by echoing specific commands to the log. 

For example, you can change the current build number to the release number from semantic-release by: 
`echo ##vso[build.updatebuildnumber]${nextRelease.version}`

I am currently doing this inside of the `@semantic-release/exec` plugin. But as nothing is returned from the call this message gets logged: 
`The command echo ##vso[build.updatebuildnumber]${nextRelease.version} wrote invalid JSON to stdout. The stdout content will be ignored.`

This, in turn, raises an error with azure pipelines because special characters are not allowed. (You can see it [here](https://dev.azure.com/DanielHabenicht/AzurePipelines-SemanticRelease/_build/results?buildId=1160&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9))

I would propose to: 
1. either drop the message for commands returning nothing but a successful exit code. (Maybe just print it for debug purposes?)
2. adding a switch to suppress this warning
3. printing the already parsed command that is executed to the info message (`The command echo ##vso[build.updatebuildnumber]1.2.3 wrote invalid JSON to stdout. The stdout content will be ignored.` would not raise the error)

**Comment by DanielHabenicht** [comment]
Thanks a lot!

**Comment by DanielHabenicht** [comment]
@pvdlg ist that a bug or a feature of semantic release posting the comment twice?

**Comment by travi** [comment]
the multiple comments are because the change was included in two independent releases.
